catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

catalog:
  '@antfu/eslint-config': ^6.7.1
  '@iconify/tools': ^5.0.0
  '@lobehub/icons-static-svg': ^1.74.0
  bumpp: ^10.3.2
  changelogithub: ^14.0.0
  eslint: ^9.39.2
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  simple-git-hooks: ^2.13.1
  taze: ^19.9.2
  tsdown: ^0.17.4
  typescript: ^5.9.3
  unplugin-unused: ^0.5.6
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
